# Generated by Django 5.1.1 on 2024-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Image', models.ImageField(upload_to='products/images/')),
                ('Quantity', models.PositiveBigIntegerField(default=0)),
                ('Sale_Price', models.DecimalField(decimal_places=2, max_digits=99, null=True)),
            ],
        ),
    ]
